(()=>{const NS="http://www.w3.org/2000/svg",norm=n=>((Math.round(n)%360)+360)%360,opp=n=>norm(n+180),fmt=n=>String(norm(n)).padStart(3,"0")+"°";
let radial=0,answerRadial=0,q=0,num=1,correct=0,wrong=0,run=0,maxrun=0,times=[],errors={},start=0,tick=null,answered=false;
function instrument(el,id){el.innerHTML=`<svg viewBox="0 0 500 500"><defs><radialGradient id="f${id}"><stop stop-color="#10233a"/><stop offset="1" stop-color="#01050b"/></radialGradient><filter id="g${id}"><feGaussianBlur stdDeviation="5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><circle cx="250" cy="250" r="218" fill="#07101c" stroke="#6f849b" stroke-width="5"/><circle cx="250" cy="250" r="207" fill="url(#f${id})" stroke="#17283b" stroke-width="3"/><circle cx="250" cy="250" r="136" fill="none" stroke="#355a7f" stroke-width="2"/><circle cx="250" cy="250" r="92" fill="none" stroke="#1d3d5f"/><line x1="250" y1="106" x2="250" y2="394" stroke="#6c839b"/><line x1="106" y1="250" x2="394" y2="250" stroke="#6c839b"/><g class="ticks"></g><g class="labels"></g><g class="moving"><line x1="250" y1="250" x2="250" y2="103" stroke="#087cff" stroke-width="9" opacity=".35" filter="url(#g${id})"/><line x1="250" y1="250" x2="250" y2="105" stroke="#118dff" stroke-width="4"/><path d="M250 88 L232 126 L250 117 L268 126 Z" fill="#35a8ff" stroke="#77c8ff" stroke-width="1.5" filter="url(#g${id})"/></g><circle cx="250" cy="250" r="29" fill="#12243a" stroke="#8299b0" stroke-width="3"/><path d="M250 229 C247 237 247 242 248 248 L235 255 L235 260 L248 257 L248 267 L243 272 L243 275 L250 273 L257 275 L257 272 L252 267 L252 257 L265 260 L265 255 L252 248 C253 242 253 237 250 229Z" fill="#fff"/><text class="readout" x="250" y="55" fill="#fff" font-size="19" text-anchor="middle">000°</text></svg>`;
const ticks=el.querySelector(".ticks"),labels=el.querySelector(".labels"),polar=(r,a)=>{let t=(a-90)*Math.PI/180;return[250+r*Math.cos(t),250+r*Math.sin(t)]};
for(let d=0;d<360;d+=5){let major=d%30===0,ten=d%10===0,[x1,y1]=polar(major?177:(ten?184:190),d),[x2,y2]=polar(202,d),l=document.createElementNS(NS,"line");Object.entries({x1,y1,x2,y2,stroke:"#fff","stroke-width":major?4:(ten?2.8:1.8)}).forEach(([k,v])=>l.setAttribute(k,v));ticks.appendChild(l)}
let card={0:"N",90:"E",180:"S",270:"W"};for(let d=0;d<360;d+=30){let t=document.createElementNS(NS,"text"),[x,y]=polar(157,d);Object.entries({x,y,fill:"#fff","font-size":card[d]?30:18,"font-weight":card[d]?800:500,"text-anchor":"middle","dominant-baseline":"middle"}).forEach(([k,v])=>t.setAttribute(k,v));t.textContent=card[d]||String(d).padStart(3,"0");labels.appendChild(t)}
return{el,moving:el.querySelector(".moving"),readout:el.querySelector(".readout")}}
const free=instrument(dial,"a"),exam=instrument(examDial,"b");
function rotate(inst,n){n=norm(n);inst.moving.setAttribute("transform",`rotate(${n} 250 250)`);inst.readout.textContent=fmt(n)}
function setFree(n){radial=norm(n);rotate(free,radial);radialOut.textContent=fmt(radial);oppOut.textContent=fmt(opp(radial))}
function setAnswer(n){answerRadial=Math.round(n);answerDisplay.textContent=String(answerRadial).padStart(3,"0")+"°";check.textContent=answerRadial<=360?"✓ Comprobar "+String(answerRadial).padStart(3,"0")+"°":"Radial no válido";check.classList.toggle("invalid",answerRadial>360)}
function buildWheel(el,max){el.innerHTML="";for(let n=0;n<=max;n++){let b=document.createElement("button");b.type="button";b.textContent=n;b.dataset.n=n;el.appendChild(b)}}
function wheelValue(el){return Math.max(0,Math.min(el.children.length-1,Math.round(el.scrollTop/58)))}
function syncWheels(){if(answered)return;setAnswer(wheelValue(wheel1)*100+wheelValue(wheel2)*10+wheelValue(wheel3))}
function resetWheels(){[wheel1,wheel2,wheel3].forEach(w=>w.scrollTop=0);setAnswer(0)}
buildWheel(wheel1,3);buildWheel(wheel2,9);buildWheel(wheel3,9);[wheel1,wheel2,wheel3].forEach(w=>{w.addEventListener("scroll",syncWheels,{passive:true});w.addEventListener("click",e=>{let b=e.target.closest("button");if(b)w.scrollTo({top:+b.dataset.n*58,behavior:"smooth"})})});
function drag(el,fn){let active=false;const point=e=>{let b=el.getBoundingClientRect(),cx=b.left+b.width/2,cy=b.top+b.height/2;fn(Math.atan2(e.clientX-cx,-(e.clientY-cy))*180/Math.PI)};el.addEventListener("pointerdown",e=>{active=true;el.setPointerCapture(e.pointerId);point(e)});el.addEventListener("pointermove",e=>{if(active)point(e)});["pointerup","pointercancel"].forEach(x=>el.addEventListener(x,()=>active=false))}
drag(dial,setFree);
minus.onclick=()=>setFree(radial-1);plus.onclick=()=>setFree(radial+1);reset.onclick=north.onclick=()=>setFree(0);swap.onclick=()=>setFree(opp(radial));

function mode(x){freePanel.hidden=x;examPanel.hidden=!x;freeTab.classList.toggle("active",!x);examTab.classList.toggle("active",x);if(x&&num===1&&!answered)newQ()}freeTab.onclick=()=>mode(false);examTab.onclick=()=>mode(true);exitExam.onclick=()=>mode(false);
function choose(){let a=Object.keys(errors).filter(k=>errors[k]>0);return a.length&&Math.random()<.35?+a[Math.floor(Math.random()*a.length)]:Math.floor(Math.random()*360)}
function timerStart(){clearInterval(tick);start=performance.now();timer.textContent="0.0 s";tick=setInterval(()=>timer.textContent=((performance.now()-start)/1000).toFixed(1)+" s",100)}
function newQ(){answered=false;next.disabled=true;q=choose();question.textContent=fmt(q);counter.textContent=`Pregunta ${num} de 20`;progressBar.style.width=(num/20*100)+"%";rotate(exam,q);resetWheels();feedback.textContent="Desliza las ruedas para seleccionar tu respuesta.";timerStart()}
function stats(){let total=correct+wrong;ok.textContent=correct;bad.textContent=wrong;accuracy.textContent=total?Math.round(correct/total*100)+"%":"—";average.textContent=times.length?(times.reduce((a,b)=>a+b,0)/times.length).toFixed(1)+" s":"—";best.textContent=times.length?Math.min(...times).toFixed(1)+" s":"—";streak.textContent=run;let a=Object.keys(errors).filter(k=>errors[k]>0).sort((a,b)=>errors[b]-errors[a]);review.textContent=a.length?a.slice(0,8).map(x=>fmt(+x)).join(" · "):"Aún no hay errores."}
check.onclick=()=>{if(answered||answerRadial>360)return;answered=true;clearInterval(tick);let s=(performance.now()-start)/1000;times.push(s);if(answerRadial===opp(q)){correct++;run++;maxrun=Math.max(maxrun,run);if(errors[q])errors[q]--;feedback.innerHTML=`<span class="good">✓ CORRECTO · ${fmt(answerRadial)}</span> · ${s.toFixed(1)} s`}else{wrong++;run=0;errors[q]=(errors[q]||0)+1;feedback.innerHTML=`<span class="badText">✕ INCORRECTO · ${fmt(answerRadial)}</span><br>Correcto: <b>${fmt(opp(q))}</b>`}stats();next.disabled=false;if(num===20)showResult()};
function showResult(){let av=(times.reduce((a,b)=>a+b,0)/times.length).toFixed(1),bt=Math.min(...times).toFixed(1);result.hidden=false;result.innerHTML=`<h2>EXAMEN COMPLETADO</h2><b>${correct}/20 correctas · ${Math.round(correct/20*100)}%</b><p>Tiempo medio ${av} s · Mejor ${bt} s · Mejor racha ${maxrun}</p>`;next.textContent="Nuevo examen"}
next.onclick=()=>{if(!answered)return;if(num===20){num=1;correct=wrong=run=maxrun=0;times=[];result.hidden=true;next.textContent="Siguiente →";stats()}else num++;newQ()};
setFree(0);setAnswer(0);stats()})();